version: '3.0'
volumes: 
  postgres_data:
services:
  rabbitmq:
    image: rabbitmq:3.8.2
    hostname: rabbitmq
    environment:
    #   RABBITMQ_DEFAULT_VHOST: "XXX"  #默认虚拟机名
       RABBITMQ_DEFAULT_USER: edgeai
       RABBITMQ_DEFAULT_PASS: p123456
    ports:
      - "15672:15672" #管理界面ui端口
      # - "4369:4369" #erlang发现口
      - "5672:5672" #client端通信口
      - "1883:1883"
      # - "25672:25672" #server间内部通信口
      
  db:
    image: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: project_development
      POSTGRES_PASSWORD: p12345678
  app:
    build:
      context: .
      
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # command: bash -c "rm -rf tmp/pids/server.pid && bundle exec  rails s  -e development -p 3000 -b '0.0.0.0' "
    # command: bash -c "rm -rf tmp/pids/server.pid && bundle exec  rails s  -e production -p 3000 -b '0.0.0.0' "
    command: bash -c "sleep 10 && rm -rf tmp/pids/server.pid && bundle exec  rails s  -e production -p 3000 -b '0.0.0.0' "

    #command: bundle exec guard -i
    #command: foreman start -f Procfile.dev -p 3000
    volumes:
      - .:/project
    ports:
      - "8011:3000"
    depends_on:
      - db
